enforce formatting with shfmt (#53)
* enforce formatting with shfmt

* run shfmt everywhere

diff --git a/bin/bs_android b/bin/bs_android
--- a/bin/bs_android
+++ b/bin/bs_android
@@ -26,46 +26,49 @@ TEMP=$(getopt -n "$0" -a -l "flavor:" -- -- "$@")
 eval set -- "$TEMP"
 while [ $# -gt 0 ]; do
 	case "$1" in
-	--flavor) FLAVOR="$2"; shift;;
-	--) shift;;
+	--flavor)
+		FLAVOR="$2"
+		shift
+		;;
+	--) shift ;;
 	esac
 	shift
 done
 
 if [ -n "$FLAVOR" ]; then
-  echo "Passed flavor: $FLAVOR"
-  FLAVOR_SUFFIXED="-$FLAVOR-"
-  FLAVOR_DIR="/$FLAVOR/"
+	echo "Passed flavor: $FLAVOR"
+	FLAVOR_SUFFIXED="-$FLAVOR-"
+	FLAVOR_DIR="/$FLAVOR/"
 fi
 # Argument parsing end
 
 if [ -z "$BROWSERSTACK_CREDS" ]; then
-    echo "Error: BROWSERSTACK_CREDS not set"
-    exit 1
+	echo "Error: BROWSERSTACK_CREDS not set"
+	exit 1
 fi
 
 if [ -z "$BROWSERSTACK_PROJECT" ]; then
-    default_project="Unnamed Android project"
-    echo "BROWSERSTACK_PROJECT not set, using default: $default_project"
-    BROWSERSTACK_PROJECT="$default_project"
+	default_project="Unnamed Android project"
+	echo "BROWSERSTACK_PROJECT not set, using default: $default_project"
+	BROWSERSTACK_PROJECT="$default_project"
 fi
 
 if [ -z "$BROWSERSTACK_ANDROID_DEVICES" ]; then
-    default_devices="[\"Google Pixel 4-10.0\"]"
-    echo "BROWSERSTACK_ANDROID_DEVICES not set, using default: $default_devices"
-    BROWSERSTACK_ANDROID_DEVICES="$default_devices"
+	default_devices="[\"Google Pixel 4-10.0\"]"
+	echo "BROWSERSTACK_ANDROID_DEVICES not set, using default: $default_devices"
+	BROWSERSTACK_ANDROID_DEVICES="$default_devices"
 fi
 
 if [ "$BROWSERSTACK_SKIP_BUILD" = 1 ]; then
-  echo "BROWSERSTACK_SKIP_BUILD set to 1, build was skipped"
+	echo "BROWSERSTACK_SKIP_BUILD set to 1, build was skipped"
 else
-  patrol build android "${original_args[@]}"
+	patrol build android "${original_args[@]}"
 fi
 
 app_path="$PWD/build/app/outputs/apk${FLAVOR_DIR}debug/app${FLAVOR_SUFFIXED}debug.apk"
 if [ ! -f "$app_path" ]; then
-  echo "Error: apk not found at $app_path"
-  exit 1
+	echo "Error: apk not found at $app_path"
+	exit 1
 fi
 
 # https://www.browserstack.com/docs/app-automate/api-reference/espresso/apps#upload-an-app
@@ -81,8 +84,8 @@ echo "Uploaded app under test, url: $app_url"
 
 test_path="$PWD/build/app/outputs/apk/androidTest${FLAVOR_DIR}debug/app${FLAVOR_SUFFIXED}debug-androidTest.apk"
 if [ ! -f "$test_path" ]; then
-  echo "Error: test apk not found at $test_path"
-  exit 1
+	echo "Error: test apk not found at $test_path"
+	exit 1
 fi
 
 # https://www.browserstack.com/docs/app-automate/api-reference/espresso/tests#upload-a-test-suite
@@ -96,13 +99,12 @@ test_upload_response="$(
 test_url="$(echo "$test_upload_response" | jq --raw-output .test_suite_url)"
 echo "Uploaded test instrumentation app, url: $test_url"
 
-
 # https://www.browserstack.com/docs/app-automate/api-reference/espresso/builds#execute-a-build
 printf "Will schedule test execution\n\n"
 curl -u "$BROWSERSTACK_CREDS" \
-  -X POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/build" \
-  -H "Content-Type: application/json" \
-  --data-binary @- <<EOF
+	-X POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/build" \
+	-H "Content-Type: application/json" \
+	--data-binary @- <<EOF
 {
     "app": "$app_url",
     "testSuite": "$test_url",
diff --git a/bin/link_changelog b/bin/link_changelog
--- a/bin/link_changelog
+++ b/bin/link_changelog
@@ -14,7 +14,7 @@ set -euo pipefail
 # For example:
 #
 # $ link_changelog some_single_package v0.7.3
-# 
+#
 # $ link_changelog leancode_contracts v2.1.0
 #
 # $ link_changelog dispose_scope-v3.0.0-dev.1
@@ -22,36 +22,35 @@ set -euo pipefail
 # $ link_changelog dispose_scope 3.0.0-dev.1 # the leading "v" can be ommitted
 
 if [ "$#" = 1 ]; then
-    tag="${1:-}"
+	tag="${1:-}"
 elif [ "$#" = 2 ]; then
-    package_name="${1:-}"
-    tag="${2:-}"
+	package_name="${1:-}"
+	tag="${2:-}"
 fi
 
 if [ -z "$tag" ]; then
-    echo "error: missing tag" 1>&2
-    exit 1
+	echo "error: missing tag" 1>&2
+	exit 1
 fi
 
 if [ -n "${package_name:-}" ]; then
-    # package name + git tag
-    version="${tag#"$package_name"}"
-    version="${version#v}"
-    version=$(echo "$version" | tr -d '.+')
+	# package name + git tag
+	version="${tag#"$package_name"}"
+	version="${version#v}"
+	version=$(echo "$version" | tr -d '.+')
 else
-    # only git tag
-    package_name="$(echo "$tag" | cut -d '-' -f 1)"
-    version="$(echo "$tag" | cut -d '-' -f 2-)"
+	# only git tag
+	package_name="$(echo "$tag" | cut -d '-' -f 1)"
+	version="$(echo "$tag" | cut -d '-' -f 2-)"
 
-    if [ "$package_name" = "$version" ]; then
-        echo "error: invalid version" 1>&2
-        exit 1
-    fi
+	if [ "$package_name" = "$version" ]; then
+		echo "error: invalid version" 1>&2
+		exit 1
+	fi
 
-    version="${version#v}"
-    version=$(echo "$version" | tr -d '.+')
+	version="${version#v}"
+	version=$(echo "$version" | tr -d '.+')
 fi
 
 link="https://pub.dev/packages/$package_name/changelog#$version"
 echo "$link"
-
