standarize error handling and stderr in bs_android

diff --git a/bin/bs_android b/bin/bs_android
--- a/bin/bs_android
+++ b/bin/bs_android
@@ -1,7 +1,10 @@
 #!/usr/bin/env bash
-set -euo pipefail
+set -uo pipefail
 
-# bs_android uploads APKs for UI testing on BrowserStack.
+# DO NOT set -e, otherwise error responses won't be shown to the user.
+
+# bs_android uploads APKs for UI testing on BrowserStack. Upon successful
+# completion, it returns build ID of the test run on BrowserStack.
 #
 # It forwards all arguments to "patrol build android", so you can pass --target,
 # --flavor, --exclude etc. just as you would pass them to "patrol_cli".
@@ -14,8 +17,7 @@ BROWSERSTACK_SKIP_BUILD="${BROWSERSTACK_SKIP_BUILD:-0}"
 BROWSERSTACK_IDLE_TIMEOUT="${BROWSERSTACK_IDLE_TIMEOUT:-900}"
 
 # Capture all arguments because they'll be consumed by getopt
-# shellcheck disable=SC2206
-original_args=($@)
+original_args=("$@")
 
 # Argument parsing start
 FLAVOR=""
@@ -36,74 +38,83 @@ while [ $# -gt 0 ]; do
 done
 
 if [ -n "$FLAVOR" ]; then
-	echo "Passed flavor: $FLAVOR"
+	echo 1>&2 "Passed flavor: $FLAVOR"
 	FLAVOR_SUFFIXED="-$FLAVOR-"
 	FLAVOR_DIR="/$FLAVOR/"
 fi
 # Argument parsing end
 
 if [ -z "$BROWSERSTACK_CREDS" ]; then
-	echo "Error: BROWSERSTACK_CREDS not set"
+	echo 1>&2 "Error: BROWSERSTACK_CREDS not set"
 	exit 1
 fi
 
 if [ -z "$BROWSERSTACK_PROJECT" ]; then
 	default_project="Unnamed Android project"
-	echo "BROWSERSTACK_PROJECT not set, using default: $default_project"
+	echo 1>&2 "BROWSERSTACK_PROJECT not set, using default: $default_project"
 	BROWSERSTACK_PROJECT="$default_project"
 fi
 
 if [ -z "$BROWSERSTACK_ANDROID_DEVICES" ]; then
 	default_devices="[\"Google Pixel 4-10.0\"]"
-	echo "BROWSERSTACK_ANDROID_DEVICES not set, using default: $default_devices"
+	echo 1>&2 "BROWSERSTACK_ANDROID_DEVICES not set, using default: $default_devices"
 	BROWSERSTACK_ANDROID_DEVICES="$default_devices"
 fi
 
 if [ "$BROWSERSTACK_SKIP_BUILD" = 1 ]; then
-	echo "BROWSERSTACK_SKIP_BUILD set to 1, build was skipped"
+	echo 1>&2 "BROWSERSTACK_SKIP_BUILD set to 1, build was skipped"
 else
-	patrol build android "${original_args[@]}"
+	1>&2 patrol build android "${original_args[@]}"
 fi
 
 app_path="$PWD/build/app/outputs/apk${FLAVOR_DIR}debug/app${FLAVOR_SUFFIXED}debug.apk"
 if [ ! -f "$app_path" ]; then
-	echo "Error: apk not found at $app_path"
+	echo 1>&2 "Error: apk not found at $app_path"
 	exit 1
 fi
 
 # https://www.browserstack.com/docs/app-automate/api-reference/espresso/apps#upload-an-app
-printf "Will upload app under test from %s\n\n" "$app_path"
-app_upload_response="$(
-	curl -u "$BROWSERSTACK_CREDS" \
-		-X POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/app" \
-		-F "file=@$app_path"
-)"
+1>&2 printf "Will upload app under test from %s\n\n" "$app_path"
+if ! app_upload_response="$(
+	curl --fail-with-body --user "$BROWSERSTACK_CREDS" \
+		--request POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/app" \
+		--form "file=@$app_path"
+)"; then
+	echo 1>&2 "Error: failed to upload app under test"
+	echo 1>&2 "$app_upload_response"
+	exit 1
+fi
 
 app_url="$(echo "$app_upload_response" | jq --raw-output .app_url)"
-echo "Uploaded app under test, url: $app_url"
+echo 1>&2 "Uploaded app under test, url: $app_url"
 
 test_path="$PWD/build/app/outputs/apk/androidTest${FLAVOR_DIR}debug/app${FLAVOR_SUFFIXED}debug-androidTest.apk"
 if [ ! -f "$test_path" ]; then
-	echo "Error: test apk not found at $test_path"
+	echo 1>&2 "Error: test apk not found at $test_path"
 	exit 1
 fi
 
 # https://www.browserstack.com/docs/app-automate/api-reference/espresso/tests#upload-a-test-suite
-printf "Will upload test instrumentation app from %s\n\n" "$test_path"
-test_upload_response="$(
-	curl --silent -u "$BROWSERSTACK_CREDS" \
-		-X POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/test-suite" \
-		-F "file=@$test_path"
-)"
+1>&2 printf "Will upload test instrumentation app from %s\n\n" "$test_path"
+if ! test_upload_response="$(
+	curl --fail-with-body --user "$BROWSERSTACK_CREDS" \
+		--request POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/test-suite" \
+		--form "file=@$test_path"
+)"; then
+	echo 1>&2 "Error: failed to upload test instrumentation app"
+	echo 1>&2 "$test_upload_response"
+	exit 1
+fi
 
 test_url="$(echo "$test_upload_response" | jq --raw-output .test_suite_url)"
-echo "Uploaded test instrumentation app, url: $test_url"
+echo 1>&2 "Uploaded test instrumentation app, url: $test_url"
 
 # https://www.browserstack.com/docs/app-automate/api-reference/espresso/builds#execute-a-build
-printf "Will schedule test execution\n\n"
-curl -u "$BROWSERSTACK_CREDS" \
-	-X POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/build" \
-	-H "Content-Type: application/json" \
+1>&2 printf "Will schedule test execution\n\n"
+if ! run_response="$(
+	curl --fail-with-body --user "$BROWSERSTACK_CREDS" \
+	--request POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/build" \
+	--header "Content-Type: application/json" \
 	--data-binary @- <<EOF
 {
     "app": "$app_url",
@@ -118,5 +129,13 @@ curl -u "$BROWSERSTACK_CREDS" \
     "idleTimeout": $BROWSERSTACK_IDLE_TIMEOUT
 }
 EOF
+)"; then
+	echo 1>&2 "Error: failed to schedule test execution"
+	echo 1>&2 "$run_response"
+	exit 1
+fi
 
-printf "\n\nScheduled test execution\n"
+printf 1>&2 "\n\nScheduled test execution\n"
+
+build_id="$(echo "$run_response" | jq --raw-output .build_id)"
+echo "$build_id"
