BROWSERSTACK_CREDS -> BROWSERSTACK_CREDENTIALS

diff --git a/bin/bs_android b/bin/bs_android
--- a/bin/bs_android
+++ b/bin/bs_android
@@ -10,7 +10,7 @@ set -uo pipefail
 # --flavor, --exclude etc. just as you would pass them to "patrol_cli".
 #
 # It can also be configured with the following environment variables:
-BROWSERSTACK_CREDS="${BROWSERSTACK_CREDS:-}"
+BROWSERSTACK_CREDENTIALS="${BROWSERSTACK_CREDENTIALS:-}"
 BROWSERSTACK_PROJECT="${BROWSERSTACK_PROJECT:-}"
 BROWSERSTACK_ANDROID_DEVICES="${BROWSERSTACK_ANDROID_DEVICES:-}"
 BROWSERSTACK_SKIP_BUILD="${BROWSERSTACK_SKIP_BUILD:-0}"
@@ -44,8 +44,8 @@ if [ -n "$FLAVOR" ]; then
 fi
 # Argument parsing end
 
-if [ -z "$BROWSERSTACK_CREDS" ]; then
-	echo 1>&2 "Error: BROWSERSTACK_CREDS not set"
+if [ -z "$BROWSERSTACK_CREDENTIALS" ]; then
+	echo 1>&2 "Error: BROWSERSTACK_CREDENTIALS not set"
 	exit 1
 fi
 
@@ -76,7 +76,7 @@ fi
 # https://www.browserstack.com/docs/app-automate/api-reference/espresso/apps#upload-an-app
 1>&2 printf "Will upload app under test from %s\n\n" "$app_path"
 if ! app_upload_response="$(
-	curl --fail-with-body --user "$BROWSERSTACK_CREDS" \
+	curl --fail-with-body --user "$BROWSERSTACK_CREDENTIALS" \
 		--request POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/app" \
 		--form "file=@$app_path"
 )"; then
@@ -97,7 +97,7 @@ fi
 # https://www.browserstack.com/docs/app-automate/api-reference/espresso/tests#upload-a-test-suite
 1>&2 printf "Will upload test instrumentation app from %s\n\n" "$test_path"
 if ! test_upload_response="$(
-	curl --fail-with-body --user "$BROWSERSTACK_CREDS" \
+	curl --fail-with-body --user "$BROWSERSTACK_CREDENTIALS" \
 		--request POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/test-suite" \
 		--form "file=@$test_path"
 )"; then
@@ -112,7 +112,7 @@ echo 1>&2 "Uploaded test instrumentation app, url: $test_url"
 # https://www.browserstack.com/docs/app-automate/api-reference/espresso/builds#execute-a-build
 1>&2 printf "Will schedule test execution\n\n"
 if ! run_response="$(
-	curl --fail-with-body --user "$BROWSERSTACK_CREDS" \
+	curl --fail-with-body --user "$BROWSERSTACK_CREDENTIALS" \
 	--request POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/build" \
 	--header "Content-Type: application/json" \
 	--data-binary @- <<EOF
diff --git a/bin/bs_ios b/bin/bs_ios
--- a/bin/bs_ios
+++ b/bin/bs_ios
@@ -13,7 +13,7 @@ set -uo pipefail
 # --flavor, --exclude etc. just as you would pass them to "patrol_cli".
 #
 # It can also be configured with the following environment variables:
-BROWSERSTACK_CREDS="${BROWSERSTACK_CREDS:-}"
+BROWSERSTACK_CREDENTIALS="${BROWSERSTACK_CREDENTIALS:-}"
 BROWSERSTACK_PROJECT="${BROWSERSTACK_PROJECT:-}"
 BROWSERSTACK_IOS_DEVICES="${BROWSERSTACK_IOS_DEVICES:-}"
 BROWSERSTACK_SKIP_BUILD="${BROWSERSTACK_SKIP_BUILD:-0}"
@@ -52,8 +52,8 @@ if [ -n "$FLAVOR" ]; then
 fi
 # Arg parsing end
 
-if [ -z "${BROWSERSTACK_CREDS:-}" ]; then
-	echo 1>&2 "Error: BROWSERSTACK_CREDS not set"
+if [ -z "${BROWSERSTACK_CREDENTIALS:-}" ]; then
+	echo 1>&2 "Error: BROWSERSTACK_CREDENTIALS not set"
 	exit 1
 fi
 
@@ -106,7 +106,7 @@ fi
 # https://www.browserstack.com/docs/app-automate/api-reference/xcuitest/apps#upload-an-app
 printf 1>&2 "Will upload app under test from %s\n\n" "$app_path"
 if ! app_upload_response="$(
-	curl --fail-with-body --user "$BROWSERSTACK_CREDS" \
+	curl --fail-with-body --user "$BROWSERSTACK_CREDENTIALS" \
 		--request POST "https://api-cloud.browserstack.com/app-automate/xcuitest/v2/app" \
 		--form "file=@$app_path"
 )"; then
@@ -127,7 +127,7 @@ fi
 # https://www.browserstack.com/docs/app-automate/api-reference/xcuitest/tests#upload-a-test-suite
 printf 1>&2 "Will upload zip archive of test suite from %s\n\n" "$test_path"
 if ! test_upload_response="$(
-	curl --fail-with-body --user "$BROWSERSTACK_CREDS" \
+	curl --fail-with-body --user "$BROWSERSTACK_CREDENTIALS" \
 		--request POST "https://api-cloud.browserstack.com/app-automate/xcuitest/v2/test-suite" \
 		--form "file=@$test_path"
 )"; then
@@ -142,7 +142,7 @@ printf 1>&2 "\nUploaded zip archive of test suite, url: %s\n" "$test_url"
 # https://www.browserstack.com/docs/app-automate/api-reference/xcuitest/builds#execute-a-build
 printf 1>&2 "Will schedule test execution\n\n"
 if ! run_response="$(
-	curl --fail-with-body --user "$BROWSERSTACK_CREDS" \
+	curl --fail-with-body --user "$BROWSERSTACK_CREDENTIALS" \
 		--request POST "https://api-cloud.browserstack.com/app-automate/xcuitest/v2/xctestrun-build" \
 		--header "Content-Type: application/json" \
 		--data-binary @- <<EOF
