rework script to work only on git tag

diff --git a/bin/link_changelog b/bin/link_changelog
--- a/bin/link_changelog
+++ b/bin/link_changelog
@@ -9,30 +9,34 @@ set -euo pipefail
 #
 # Usage:
 #
-# $ link_changelog <package_name> <git_tag>
+# $ link_changelog <git_tag>
 #
 # For example:
 #
-# $ link_changelog some_single_package v0.7.3
+# $ link_changelog some_single_package-v0.7.3
 # 
-# $ link_changelog leancode_contracts leancode_contracts-v2.1.0
+# $ link_changelog leancode_contracts-v2.1.0
+#
+# $ link_changelog dispose_scope-v3.0.0-dev.1
 
-package_name="${1:-}"
-tag="${2:-}"
-
-if [ -z "$package_name" ]; then
-    echo "error: missing package name" 1>&2
-    exit 1
-fi
+tag="${1:-}"
+print_markdown="${2:-}"
 
 if [ -z "$tag" ]; then
     echo "error: missing tag" 1>&2
     exit 1
 fi
 
-prefix="${3:-${package_name}-}"
-version="${tag#$prefix}"
+package_name="$(echo $tag | cut -d '-' -f 1)"
+version="$(echo $tag | cut -d '-' -f 2)"
+
+if [ "$package_name" = "$version" ]; then
+    echo "error: invalid version" 1>&2
+    exit 1
+fi
+
 version="${version#v}"
-version=$(echo "$version" | tr -d '.+')
-link="https://pub.dev/packages/$package_name/changelog#$version"
+version_int=$(echo "$version" | tr -d '.+')
+
+link="https://pub.dev/packages/$package_name/changelog#$version_int"
 echo "$link"
