allow for 1 or 2 param option in a backward-compatible way!

diff --git a/bin/link_changelog b/bin/link_changelog
--- a/bin/link_changelog
+++ b/bin/link_changelog
@@ -19,24 +19,39 @@ set -euo pipefail
 #
 # $ link_changelog dispose_scope-v3.0.0-dev.1
 
-tag="${1:-}"
-print_markdown="${2:-}"
+if [ "$#" = 1 ]; then
+    tag="${1:-}"
+elif [ "$#" = 2 ]; then
+    package_name="${1:-}"
+    tag="${2:-}"
+fi
 
 if [ -z "$tag" ]; then
     echo "error: missing tag" 1>&2
     exit 1
 fi
 
-package_name="$(echo $tag | cut -d '-' -f 1)"
-version="$(echo $tag | cut -d '-' -f 2)"
+if [ -n "${package_name:-}" ]; then
+    # package name + git tag
+    version="${tag#$package_name}"
+    version="${version#v}"
+    version=$(echo "$version" | tr -d '.+')
+    link="https://pub.dev/packages/$package_name/changelog#$version"
+    echo "$link"
+else
+    # only git tag
+    package_name="$(echo $tag | cut -d '-' -f 1)"
+    version="$(echo $tag | cut -d '-' -f 2)"
 
-if [ "$package_name" = "$version" ]; then
-    echo "error: invalid version" 1>&2
-    exit 1
+    if [ "$package_name" = "$version" ]; then
+        echo "error: invalid version" 1>&2
+        exit 1
+    fi
+
+    version="${version#v}"
+    version_int=$(echo "$version" | tr -d '.+')
+
+    link="https://pub.dev/packages/$package_name/changelog#$version_int"
+    echo "$link"
 fi
 
-version="${version#v}"
-version_int=$(echo "$version" | tr -d '.+')
-
-link="https://pub.dev/packages/$package_name/changelog#$version_int"
-echo "$link"
