Infer package name from git tag if possible (#23)

diff --git a/bin/link_changelog b/bin/link_changelog
--- a/bin/link_changelog
+++ b/bin/link_changelog
@@ -9,20 +9,21 @@ set -euo pipefail
 #
 # Usage:
 #
-# $ link_changelog <package_name> <git_tag>
+# $ link_changelog <git_tag>
 #
 # For example:
 #
 # $ link_changelog some_single_package v0.7.3
 # 
-# $ link_changelog leancode_contracts leancode_contracts-v2.1.0
+# $ link_changelog leancode_contracts v2.1.0
+#
+# $ link_changelog dispose_scope-v3.0.0-dev.1
 
-package_name="${1:-}"
-tag="${2:-}"
-
-if [ -z "$package_name" ]; then
-    echo "error: missing package name" 1>&2
-    exit 1
+if [ "$#" = 1 ]; then
+    tag="${1:-}"
+elif [ "$#" = 2 ]; then
+    package_name="${1:-}"
+    tag="${2:-}"
 fi
 
 if [ -z "$tag" ]; then
@@ -30,9 +31,25 @@ if [ -z "$tag" ]; then
     exit 1
 fi
 
-prefix="${3:-${package_name}-}"
-version="${tag#$prefix}"
-version="${version#v}"
-version=$(echo "$version" | tr -d '.+')
+if [ -n "${package_name:-}" ]; then
+    # package name + git tag
+    version="${tag#"$package_name"}"
+    version="${version#v}"
+    version=$(echo "$version" | tr -d '.+')
+else
+    # only git tag
+    package_name="$(echo "$tag" | cut -d '-' -f 1)"
+    version="$(echo "$tag" | cut -d '-' -f 2-)"
+
+    if [ "$package_name" = "$version" ]; then
+        echo "error: invalid version" 1>&2
+        exit 1
+    fi
+
+    version="${version#v}"
+    version=$(echo "$version" | tr -d '.+')
+fi
+
 link="https://pub.dev/packages/$package_name/changelog#$version"
 echo "$link"
+
